"""empty message

Revision ID: 2cdf6dc336b8
Revises: a421de5b9b21
Create Date: 2021-09-02 10:13:21.992753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdf6dc336b8'
down_revision = 'a421de5b9b21'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', naming_convention=naming_convention, schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_type_pk_game_type', type_='foreignkey')
        batch_op.drop_constraint('fk_game_result_pk_game_result', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_game_result_pk_game_result', 'game_result', ['result_pk'], ['result'])
        batch_op.create_foreign_key('fk_game_type_pk_game_type', 'game_type', ['type_pk'], ['type'])

    # ### end Alembic commands ###
