"""initial migrations

Revision ID: 5a78f074149f
Revises: 
Create Date: 2021-08-24 17:38:14.525735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a78f074149f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('color')
    )
    op.create_table('game_result',
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('result')
    )
    op.create_table('game_type',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('fen', sa.String(length=100), nullable=True),
    sa.Column('moves', sa.String(length=100), nullable=True),
    sa.Column('type_pk', sa.String(length=100), nullable=False),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('result_pk', sa.String(), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_pk'], ['game_result.result'], ),
    sa.ForeignKeyConstraint(['type_pk'], ['game_type.type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pc_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color'], ['color.color'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('pc_game')
    op.drop_table('online_game')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('game_type')
    op.drop_table('game_result')
    op.drop_table('color')
    # ### end Alembic commands ###
