"""add last seen column

Revision ID: 7623acbbf86a
Revises: db79eb753dbc
Create Date: 2021-11-09 22:50:29.773532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7623acbbf86a'
down_revision = 'db79eb753dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
