"""added draw_offered column

Revision ID: c0d8d72d5c34
Revises: 2330c665ec46
Create Date: 2021-09-07 09:34:33.623562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d8d72d5c34'
down_revision = '2330c665ec46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draw_offered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_column('draw_offered')

    # ### end Alembic commands ###
